# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vidha Saumya
email: vidhasaumya@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Vidha Saumya is a drawer, cook, and a bookmaker. She seeks visual interest in the idea of congregating bodies, popular culture and the notion of deformity. She has held solo exhibitions and participated in group exhibitions in Lahore, Mumbai, Helsinki, and Tampere. She is the co-founder of Museum of Impossible Forms, Helsinki, where she heads ‘The m{if} Publishing Table’ – a project that seeks to actively engage with artists, writers and practitioners through book making. She is currently pursuing Master’s Degree in Visual Culture and Contemporary Art at Aalto University, Helsinki.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

social:
  email: vidhasaumya@gmail.com
  facebook: https://www.facebook.com/vidha.saumya
  linkedin: https://www.linkedin.com/in/vidha-saumya-9763a4114/
  instagram-dossier: https://www.instagram.com/whatismissinginmydossier/
  instagram-vidheshawri: https://www.instagram.com/vidheshwari/

# Collections
collections:
  pages:
    output: true
  projects:
    output: true
  content:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
